### ISSUE TITLE
How can I deal with memory problem?

### ISSUE THREAD

**Issue by rightx2** [FeatureLabs/featuretools#829]
### Bug/Feature Request Title

I got a bunch of WARNING messages during `dfs` process. Here is the code:

```
features= ft.dfs(
    entityset=es,
    target_entity='stores',
    cutoff_time=data_df[['store_id', 'cutoff_time', '3month_amount_from_cutoff_time']],
    verbose=1,
    cutoff_time_in_index=True,
    n_jobs=16,
    max_depth=2,
    ignore_variables={
        'sales':['sale_id'],
    },
    agg_primitives=[
        "sum", "std", "max","skew", "min", "mean", "median", "count", "percent_true", "num_unique", "mode", "trend", "time_since_last", "time_since_first",
        "first", "last", "entropy", "avg_time_between",
        "n_most_common",
        # "any", "all", "num_true",
    ],
    groupby_trans_primitives=[
        'cum_mean', 'cum_sum', 'cum_min', 'cum_max', 'cum_count',
        'year', 'month',
        'diff', 'haversine', 'is_null', 'percentile',
        'time_since', 'time_since_previous',
    ],
    trans_primitives=[],
    chunk_size=200,
)

# data_df.shape => (61034, 101)
# dataframe in es's shape
#    - es['stores'].shape => (1967, 6)
#    - es['sales'].shape => (6556613, 6)
```

And WARNING messages I've got:
```
...
...
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 12.89 GB -- Worker memory limit: 16.54 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 11.98 GB -- Worker memory limit: 16.54 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 12.89 GB -- Worker memory limit: 16.54 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 11.98 GB -- Worker memory limit: 16.54 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 12.52 GB -- Worker memory limit: 16.54 GB
...
...

```

-----

#### Bug/Feature Request Description
These WARNING start to show up around 45% in progress bar. I know these are WARNING, but problem is that it finally makes `dfs` stop running after a few hours later...(raise errors!)

I have enough memory (256GB), the number of cpu (64) but I don't see why it still requires more memory despite of its small memory size. 

And when finally `dfs` is stopped, error messages is like this:
```
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.worker - ERROR - 'EntitySet-dcc40d75cfac8a5e5765e5bba8aeeb7a'
Traceback (most recent call last):
  File "/data/miniconda3/lib/python3.7/site-packages/distributed/worker.py", line 2408, in execute
    data[k] = self.data[k]
  File "/data/miniconda3/lib/python3.7/site-packages/zict/buffer.py", line 72, in __getitem__
    raise KeyError(key)
KeyError: 'EntitySet-dcc40d75cfac8a5e5765e5bba8aeeb7a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/miniconda3/lib/python3.7/site-packages/distributed/worker.py", line 2412, in execute
    data[k] = Actor(type(self.actors[k]), self.address, k, self)
KeyError: 'EntitySet-dcc40d75cfac8a5e5765e5bba8aeeb7a'
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fb344b70ed0>>, <Task finished coro=<
Worker.execute() done, defined at /data/miniconda3/lib/python3.7/site-packages/distributed/worker.py:2391> exception=KeyError('EntitySet-dcc40d75cfac8a5e5765e5bba8aeeb7a')>)
Traceback (most recent call last):
  File "/data/miniconda3/lib/python3.7/site-packages/distributed/worker.py", line 2408, in execute
    data[k] = self.data[k]
  File "/data/miniconda3/lib/python3.7/site-packages/zict/buffer.py", line 72, in __getitem__
    raise KeyError(key)
KeyError: 'EntitySet-dcc40d75cfac8a5e5765e5bba8aeeb7a'
```

Moreover, error messages are different time to time: `connection closed error` some time,  `Stream is closed` or  `distributed.nanny - WARNING - Worker exceeded 95% memory budget` etc.

I wonder what should I do to prevent this from occuring:

Reducing `chunk_size` more? or Reducing `n_jobs` more? Or any other methods?

Which one is a more desirable way to make `dfs` done till it finishes completely?

#### Output of ``featuretools.show_info()``
```
Featuretools version: 0.12.0
Featuretools installation directory: /data/miniconda3/lib/python3.7/site-packages/featuretools

SYSTEM INFO
-----------
python: 3.7.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-1054-aws
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.17.2
pandas: 0.25.1
tqdm: 4.36.1
PyYAML: 5.1.2
cloudpickle: 1.2.2
dask: 2.6.0
distributed: 2.6.0
psutil: 5.6.3
Click: 7.0
scikit-learn: 0.21.3
pip: 19.2.3
setuptools: 41.4.0
```

**Comment by rwedge** [comment]
The warnings are about the workers approaching their individual memory limit.  Reducing n_jobs will increase the amount of memory available to each worker.  If you install the bokeh library you can use  [distributed's web interface](https://distributed.dask.org/en/latest/web.html) to monitor the process.

**Comment by rightx2** [comment]
@rwedge You mean, no matter what `chunk_size` it is, reducing `n_jobs` will solve this problem?

**Comment by kmax12** [comment]
Once, #783 is merged it, would be curious to hear if that solves this problem. 

I'm going to close this issue since there's nothing actionable for us right now
