### ISSUE TITLE
Equal, NotEqual primitives error when comparing date, object columns bug

### ISSUE THREAD

**Issue by hawksung1** [FeatureLabs/featuretools#944]
### Equal, NotEqual primitives error when comparing date, object columns bug

-----
#### Bug/Feature Request Description
featuretools dfs run equal with column type date, object
make err

#### CODE
```
import featuretools as ft
from sklearn.datasets import load_boston
import pandas as pd
from datetime import datetime, timedelta
import random


def load_data_boston():
    boston = load_boston()
    x = pd.DataFrame(boston.data)
    x.columns = boston.feature_names
    y = pd.DataFrame(boston.target)
    y.columns = ['TARGET']
    return x, y


def _gen_datetime(min_year=1900, max_year=datetime.now().year):
    # generate a datetime in format yyyy-mm-dd hh:mm:ss.000000
    start = datetime(min_year, 1, 1, 00, 00, 00)
    years = max_year - min_year + 1
    end = start + timedelta(days=365 * years)
    return start + (end - start) #* random.random()


def make_date_column(data, row_number, column_name):
    result = data
    tmp_lst = []

    for i in range(row_number):
        append_data = _gen_datetime()
        tmp_lst.append(append_data)
    result.loc[:, column_name] = pd.Series(tmp_lst, index=result.index)
    return result


def run():
    x, y = load_data_boston()
    # convert CHAS, RAD to categorical
    x['B'] = x['B'].astype('object')
    make_date_column(x, len(x), 'date1')
    # make es
    es = ft.EntitySet(id='es')
    es.entity_from_dataframe(entity_id='data', dataframe=x, make_index=True, index='_index_')    # run dfs
    result, _ = ft.dfs(entityset=es, max_depth=1, target_entity='data', trans_primitives=[ "equal"])
    return result


if __name__ == "__main__":
    run()
```
#### err
```
Traceback (most recent call last):
  File "C:/Users/hyun/PycharmProjects/untitled/featuretools_bug.py", line 49, in <module>
    run()
  File "C:/Users/hyun/PycharmProjects/untitled/featuretools_bug.py", line 44, in run
    result, _ = ft.dfs(entityset=es, max_depth=1, target_entity='data', trans_primitives=[ "equal"])
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\utils\entry_point.py", line 40, in function_wrapper
    raise e
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\utils\entry_point.py", line 32, in function_wrapper
    return_value = func(*args, **kwargs)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\synthesis\dfs.py", line 276, in dfs
    progress_callback=progress_callback)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 281, in calculate_feature_matrix
    progress_callback=progress_callback)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 378, in calculate_chunk
    training_window=window)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\computational_backends\utils.py", line 32, in wrapped
    r = method(*args, **kwargs)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\computational_backends\calculate_feature_matrix.py", line 349, in calc_results
    matrix = calculator.run(ids, progress_callback=update_progress_callback)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py", line 111, in run
    progress_callback=progress_callback)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py", line 294, in _calculate_features_for_entity
    df = self._calculate_features(df, df_trie, not_full_entity_features, progress_callback)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py", line 309, in _calculate_features
    df = handler(group, df, df_trie, progress_callback)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\featuretools\computational_backends\feature_set_calculator.py", line 422, in _calculate_transform_features
    values = feature_func(*variable_data)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\pandas\core\series.py", line 636, in __array_ufunc__
    self, ufunc, method, *inputs, **kwargs
  File "pandas\_libs\ops_dispatch.pyx", line 88, in pandas._libs.ops_dispatch.maybe_dispatch_ufunc_to_dunder_op
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\pandas\core\ops\common.py", line 64, in new_method
    return method(self, other)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\pandas\core\ops\__init__.py", line 529, in wrapper
    res_values = comparison_op(lvalues, rvalues, op)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\pandas\core\ops\array_ops.py", line 247, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "C:\Users\hyun\PycharmProjects\untitled\python3.7_test\lib\site-packages\pandas\core\ops\array_ops.py", line 57, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas\_libs\ops.pyx", line 84, in pandas._libs.ops.scalar_compare
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

#### Expected Output
not err result

#### Output of ``featuretools.show_info()``

<details>
[paste the output of ``featuretools.show_info()`` here below this line]

Featuretools version: 0.14.0
Featuretools installation directory: c:\users\hyun\pycharmprojects\untitled\python3.7_test\lib\site-packages\featuretools
SYSTEM INFO
-----------
python: 3.7.7.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
INSTALLED VERSIONS
------------------
numpy: 1.18.4
pandas: 1.0.3
tqdm: 4.46.0
PyYAML: 5.3.1
cloudpickle: 1.4.1
dask: 2.15.0
distributed: 2.15.2
psutil: 5.7.0
pip: 19.2.3
setuptools: 41.2.0

</details>

**Comment by rwedge** [comment]
Thanks for the bug report and reproducible code, @hawksung1 .  This issue seems related to #845, in that it occurs when the Equal primitive fails to compare different data types.  One possible solution to handle both of these errors would be to change the `Equal` primitive so that instead of comparing any column to any other column, it only compares columns that have the same variable type (e.g. `Equal(NOX, RM)` would be a valid feature but `Equal(NOX, date1)` would not.  This would avoid these comparison errors

**Comment by hawksung1** [comment]
@rwedge 
of course I can handle this problem as you said.
but I think that featuretools automatically compare which is possible.
It should not make errors. so I issued it as bug.
isn't it??
if not plz tell me
thanks

**Comment by rwedge** [comment]
@hawksung1,
It is a bug, and we're looking into it
